### ISSUE TITLE
add information on what CI is running

### ISSUE THREAD

**Issue by amir-arad** [watson/is-ci#10]
I want to use this module to customize the behavior of my product to fit the environment.

I would be helpful If I could get the name of the CI environment I'm running in, not just a boolean flag.

**Comment by watson** [comment]
Do you need the name as a string, or would you just want to know by comparing against a constant for each server? E.g. `if (ci.TRAVIS) {...}`

**Comment by amir-arad** [comment]
[this is my use case](https://github.com/wix/mocha-env-reporter/blob/6f0880d9fbfa471b4dfeeeba79dce9169ccefb33/get-reporter-name.js) , in which I use a string enum to mark the execution environment.

**Comment by watson** [comment]
What would happen in the case where it can't be determined which CI the code was running on, but it's still pretty obvious that it's a CI? - e.g. if the `CI` environment variable is set, but none of the other matches

**Comment by amir-arad** [comment]
that's a good question. 
In the unrealistic case of multiple concrete CI matches, returning an array with all relevant matches may be ok (at least it's truthy so it's backwards- compatible)
I the case you described, returning "unknown CI" can be acceptable.
In these scenarios my use case won't benefit from the info, but it's still better than nothing.

**Comment by watson** [comment]
I've just created the module [ci-info](https://github.com/watson/ci-info) which you can use to do this. 

I've also update this module to now depend on ci-info so that all the detection logic is in only one place. I think that's better than completely changing the API of this module.

I'll close this issue for now, but feel free to open another on the ci-info module in case something doesn't work as expected 😃

**Comment by amir-arad** [comment]
thanks!
